apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ilt0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ilt0
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ilt0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ilt0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ilt0
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vxzm-tenant/rhtap-demo-app/hacbs-test-project-ilt0@sha256:67efc1a1ecad1463c3706db1dbdb01e950e01590e9a5ef353b7214d6647e7d03
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
